"""add organization and job_title

Revision ID: 23af8584a322
Revises: 2a6d9f1c8b3e
Create Date: 2026-05-19 22:29:01.094494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23af8584a322'
down_revision: Union[str, None] = '2a6d9f1c8b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_analysis_runs_commit_sha")
    op.execute("DROP INDEX IF EXISTS ix_analysis_runs_contribution_cache")
    op.add_column('users', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'organization')
    op.create_index('ix_analysis_runs_contribution_cache', 'analysis_runs', ['repository_id', 'branch', 'commit_sha', 'analysis_scope', 'status'], unique=False)
    op.create_index('ix_analysis_runs_commit_sha', 'analysis_runs', ['repository_id', 'branch', 'commit_sha', 'status'], unique=False)
    # ### end Alembic commands ###
