"""Create technical_tasks table

Revision ID: 34177b1b2f35
Revises: f1b95144f4c8
Create Date: 2026-05-20 00:49:59.975159

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34177b1b2f35'
down_revision: Union[str, None] = 'f1b95144f4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', postgresql.ENUM('backend', 'frontend', 'qa', name='developerspecialization', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', name='taskstatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('ac_ids', sa.JSON(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_tasks_id'), 'technical_tasks', ['id'], unique=False)
    op.drop_index('ix_story_assignments_id', table_name='story_assignments')
    op.drop_table('story_assignments')
    op.alter_column('user_stories', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_stories', 'feature',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_stories', 'benefit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_stories', 'acceptance_criteria',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_stories', 'priority',
               existing_type=postgresql.ENUM('critical', 'high', 'medium', 'low', name='storypriority'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user_stories', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint('user_stories_document_id_fkey', 'user_stories', type_='foreignkey')
    op.create_foreign_key(None, 'user_stories', 'requirement_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_stories', 'backend_tasks')
    op.drop_column('user_stories', 'created_at')
    op.drop_column('user_stories', 'frontend_tasks')
    op.drop_column('user_stories', 'testing_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('testing_tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('frontend_tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('backend_tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_stories', type_='foreignkey')
    op.create_foreign_key('user_stories_document_id_fkey', 'user_stories', 'requirement_documents', ['document_id'], ['id'])
    op.alter_column('user_stories', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_stories', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('critical', 'high', 'medium', 'low', name='storypriority'),
               nullable=True)
    op.alter_column('user_stories', 'acceptance_criteria',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_stories', 'benefit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_stories', 'feature',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_stories', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('story_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('developer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('assigned', 'in_progress', 'completed', 'blocked', name='assignmentstatus'), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name='story_assignments_assigned_by_id_fkey'),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], name='story_assignments_developer_id_fkey'),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], name='story_assignments_story_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='story_assignments_pkey')
    )
    op.create_index('ix_story_assignments_id', 'story_assignments', ['id'], unique=False)
    op.drop_index(op.f('ix_technical_tasks_id'), table_name='technical_tasks')
    op.drop_table('technical_tasks')
    # ### end Alembic commands ###
