"""Add PRD and Assignment models

Revision ID: 4e9c16bb0de0
Revises: 2a6d9f1c8b3e
Create Date: 2026-05-19 18:49:21.096369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9c16bb0de0'
down_revision: Union[str, None] = '2a6d9f1c8b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'markdown', 'excel', name='documenttype'), nullable=False),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('llm_model_used', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'extracted', 'failed', name='documentstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_documents_id'), 'requirement_documents', ['id'], unique=False)
    op.create_table('user_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('story_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('feature', sa.String(), nullable=True),
    sa.Column('benefit', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='storypriority'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['requirement_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_id'), 'user_stories', ['id'], unique=False)
    op.create_table('story_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', 'blocked', name='assignmentstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_assignments_id'), 'story_assignments', ['id'], unique=False)
    op.execute("DROP INDEX IF EXISTS ix_analysis_runs_commit_sha")
    op.execute("DROP INDEX IF EXISTS ix_analysis_runs_contribution_cache")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_analysis_runs_contribution_cache', 'analysis_runs', ['repository_id', 'branch', 'commit_sha', 'analysis_scope', 'status'], unique=False)
    op.create_index('ix_analysis_runs_commit_sha', 'analysis_runs', ['repository_id', 'branch', 'commit_sha', 'status'], unique=False)
    op.drop_index(op.f('ix_story_assignments_id'), table_name='story_assignments')
    op.drop_table('story_assignments')
    op.drop_index(op.f('ix_user_stories_id'), table_name='user_stories')
    op.drop_table('user_stories')
    op.drop_index(op.f('ix_requirement_documents_id'), table_name='requirement_documents')
    op.drop_table('requirement_documents')
    # ### end Alembic commands ###
