"""Remove raw_text and llm_model columns

Revision ID: 5e27112e4577
Revises: f2ae223e2bc2
Create Date: 2026-05-19 20:50:05.310410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e27112e4577'
down_revision: Union[str, None] = 'f2ae223e2bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement_documents', 'llm_model_used')
    op.drop_column('requirement_documents', 'raw_extracted_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_documents', sa.Column('raw_extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('requirement_documents', sa.Column('llm_model_used', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
