"""add work_email to User

Revision ID: 625774a8a861
Revises: 5528deaec14b
Create Date: 2026-03-02 03:30:35.250361

"""
#upgrade migrations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625774a8a861'
down_revision: Union[str, None] = '5528deaec14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('work_email', sa.String(), nullable=False,server_default='unknown@example.com'))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_work_email'), 'users', ['work_email'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_work_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'work_email')
    # ### end Alembic commands ###
