"""add_status_and_ai_insights_to_analysis_run

Revision ID: 8d0d9c5fc812
Revises: 561998b35b63
Create Date: 2026-04-22 19:02:22.278223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0d9c5fc812'
down_revision: Union[str, None] = 'ecf430efc5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('ai_insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_runs', 'ai_insights')
    op.drop_constraint("fk_analysis_runs_user_id", "analysis_runs", type_="foreignkey")
    # ### end Alembic commands ###
