""" recruiter_fields

Revision ID: c6fe7e863631
Revises: a1b2c3d4e5f6
Create Date: 2026-05-25 00:39:00.369036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fe7e863631'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('DROP INDEX IF EXISTS uq_repository_analyses_repo_user'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS hiring_focus VARCHAR'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS security_score_visible BOOLEAN'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS high_priority_threshold INTEGER'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS weight_code_quality INTEGER'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS weight_security INTEGER'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS weight_git_activity INTEGER'))
    op.execute(sa.text('ALTER TABLE users ADD COLUMN IF NOT EXISTS weight_requirements INTEGER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_requirements')
    op.drop_column('users', 'weight_git_activity')
    op.drop_column('users', 'weight_security')
    op.drop_column('users', 'weight_code_quality')
    op.drop_column('users', 'high_priority_threshold')
    op.drop_column('users', 'security_score_visible')
    op.drop_column('users', 'hiring_focus')
    op.drop_column('users', 'department')
    op.create_index('uq_repository_analyses_repo_user', 'repository_analyses', ['repository_id', 'user_id'], unique=True)
    # ### end Alembic commands ###
