"""add github avatar url

Revision ID: dc7c76606624
Revises: o1p2q3r4s5t6
Create Date: 2026-06-26 06:53:23.740783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7c76606624'
down_revision: Union[str, None] = 'o1p2q3r4s5t6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ac_coverage_results_id'), 'ac_coverage_results', ['id'], unique=False)
    op.create_index(op.f('ix_code_embedding_records_id'), 'code_embedding_records', ['id'], unique=False)
    op.drop_index('ix_code_metrics_user_id', table_name='code_metrics')
    op.drop_column('code_metrics', 'attributed_contributors')
    op.drop_column('code_metrics', 'attribution_source')
    op.drop_index('ix_security_findings_user_id', table_name='security_findings')
    op.drop_column('security_findings', 'end_line')
    op.drop_column('security_findings', 'end_column')
    op.drop_column('security_findings', 'attribution_source')
    op.drop_column('security_findings', 'package_version')
    op.drop_column('security_findings', 'vulnerability_id')
    op.drop_column('security_findings', 'start_line')
    op.drop_column('security_findings', 'attributed_contributors')
    op.drop_column('security_findings', 'manifest_file')
    op.drop_column('security_findings', 'package_name')
    op.drop_column('security_findings', 'advisory_id')
    op.drop_column('security_findings', 'raw_metadata')
    op.drop_column('security_findings', 'start_column')
    op.drop_index('ix_sonar_analysis_summaries_analysis_run_id', table_name='sonar_analysis_summaries')
    op.drop_index('ix_sonar_file_measures_analysis_run_id', table_name='sonar_file_measures')
    op.drop_index('ix_sonar_issues_analysis_run_id', table_name='sonar_issues')
    op.drop_column('sonar_issues', 'end_line')
    op.drop_column('sonar_issues', 'end_column')
    op.drop_column('sonar_issues', 'start_line')
    op.drop_column('sonar_issues', 'start_column')
    op.create_index(op.f('ix_story_coverage_summaries_id'), 'story_coverage_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_task_embedding_records_id'), 'task_embedding_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_embedding_records_id'), table_name='task_embedding_records')
    op.drop_index(op.f('ix_story_coverage_summaries_id'), table_name='story_coverage_summaries')
    op.add_column('sonar_issues', sa.Column('start_column', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sonar_issues', sa.Column('start_line', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sonar_issues', sa.Column('end_column', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sonar_issues', sa.Column('end_line', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_sonar_issues_analysis_run_id', 'sonar_issues', ['analysis_run_id'], unique=False)
    op.create_index('ix_sonar_file_measures_analysis_run_id', 'sonar_file_measures', ['analysis_run_id'], unique=False)
    op.create_index('ix_sonar_analysis_summaries_analysis_run_id', 'sonar_analysis_summaries', ['analysis_run_id'], unique=False)
    op.add_column('security_findings', sa.Column('start_column', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('raw_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('advisory_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('package_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('manifest_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('attributed_contributors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('start_line', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('vulnerability_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('package_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('attribution_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('end_column', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('security_findings', sa.Column('end_line', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_security_findings_user_id', 'security_findings', ['user_id'], unique=False)
    op.add_column('code_metrics', sa.Column('attribution_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('code_metrics', sa.Column('attributed_contributors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_code_metrics_user_id', 'code_metrics', ['user_id'], unique=False)
    op.drop_index(op.f('ix_code_embedding_records_id'), table_name='code_embedding_records')
    op.drop_index(op.f('ix_ac_coverage_results_id'), table_name='ac_coverage_results')
    # ### end Alembic commands ###
