"""add github_access_token

Revision ID: ecf430efc5b6
Revises: c4d5e6f7a8b9
Create Date: 2026-04-22 07:51:48.403541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf430efc5b6'
down_revision: Union[str, None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    user_columns = {c["name"] for c in inspector.get_columns("users")}

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('refresh_tokens_token_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    if 'github_access_token' not in user_columns:
        op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    user_columns = {c["name"] for c in inspector.get_columns("users")}

    # ### commands auto generated by Alembic - please adjust! ###
    if 'github_access_token' in user_columns:
        op.drop_column('users', 'github_access_token')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_key', 'refresh_tokens', ['token'])
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
