"""...

Revision ID: ee554c59539a
Revises: 8d0d9c5fc812
Create Date: 2026-04-24 13:03:18.818548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee554c59539a'
down_revision: Union[str, None] = '8d0d9c5fc812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_analysis_runs_user_id",
        "analysis_runs",
        "users",
        ["user_id"],
        ["id"]
    )
    op.drop_column('repositories', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('repositories_owner_id_fkey', 'repositories', 'users', ['owner_id'], ['id'])
    op.drop_constraint("fk_analysis_runs_user_id", "analysis_runs", type_="foreignkey")
    op.drop_column('analysis_runs', 'user_id')
    # ### end Alembic commands ###
