"""Add technical tasks columns

Revision ID: f2ae223e2bc2
Revises: 4e9c16bb0de0
Create Date: 2026-05-19 19:48:07.991928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ae223e2bc2'
down_revision: Union[str, None] = '4e9c16bb0de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('backend_tasks', sa.JSON(), nullable=True))
    op.add_column('user_stories', sa.Column('frontend_tasks', sa.JSON(), nullable=True))
    op.add_column('user_stories', sa.Column('testing_tasks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories', 'testing_tasks')
    op.drop_column('user_stories', 'frontend_tasks')
    op.drop_column('user_stories', 'backend_tasks')
    # ### end Alembic commands ###
